const PRIMARY_COLOR = 'rgba(213, 67,140, 1)';
const BUTTON = PRIMARY_COLOR;
const TAB_BAR_COLOR = PRIMARY_COLOR;
const BACKGROUND = 'rgba(255,255,255, 1)';
const TEXT_FIELD = 'rgba(88, 184, 172, 1)';
const BUTTON_TEXT = '#fff';
const ERROR_TEXT = '#ff0033';
const BORDER = 'rgba(235, 235, 235, 1)';

export {
  BUTTON,
  BACKGROUND,
  TEXT_FIELD,
  BUTTON_TEXT,
  ERROR_TEXT,
  TAB_BAR_COLOR,
  BORDER,
  PRIMARY_COLOR,
};
